
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import NavBar from '@/components/navBar/NavBar'
import ConnectMetaMaskButton from '@/components/connect/ConnectMetaMaskButton'
import Image from 'next/image'
import Atropos from 'atropos/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next DaPP',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;900&family=Roboto+Mono:wght@400;900&family=Roboto:wght@400;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
          <NavBar />
        {children}
      </body>
    </html>
  )
}
